### PR TITLE
Bug 10 from list redsword on maps

### PR DESCRIPTION
**Pull request by Shadowss**

### CODE REVIEW

**Comment by Shadowss** [comment]
This is the solution but i don`t know what is wrong in that code , redswords doesn`t apper on map .... and i don`t know WHY

**Comment by noonn** [comment]
show me the error(bug) image?

**Comment by Shadowss** [comment]
It`s no error simply not show what must show

**Comment by Shadowss** [comment]
It must to view like this : http://www.youtube.com/watch?v=fG88EFOCkVw

I implement all , function checkAttaks , checkEnforce , and all code , and i do not know why do not work ....

**Comment by yi12345** [comment]
i tried it too, but i didn't made it because it didn't work, so i close it for now...

**Pull request closed without merging**
