### PR TITLE
fix starvation , now work like real travian

### PR DESCRIPTION
**Pull request by Shadowss**

### CODE REVIEW

**Comment by eliopinho** [comment]
nice :)
:+1:

**Comment by eliopinho** [comment]
hi mate i test it and dont work :/ troop not die :(

**Comment by Shadowss** [comment]
@eliopinho : THIS MODE WORKS LIKE REAL TRAVIAN !!! NOTICE LIKE REAL TRAVIAN !!!!

DO NOT ADD TROOPS FROM ADMIN PANEL !!!! IF YOU ADD TROOPS FROM ADMIN PANEL WILL NOT WORK !!! PLAY FAIR !!!

Notice mode will start work after :
1. Build complete : finish a building
2. Return unit complete : after units return from battle or return from other player
3. Send unit complete : after attack , etc
4. Return reinforcement complete : after reinforcement arive or retred from other village or after someone send you reinforcement
5. Training complete : after train troops over your crop capacity.

So you must play fair , like real travian. Don`t say don`t work if you don`t know how it`s work , it`s simple to afirm something that you don`t know

**Comment by Shadowss** [comment]
Also works in offline mode , online mode , etc

How to test : make a new village and leave 2 population without upgrade cropland. And send 3000 troops from other village. Starvation will start work ;)

**Comment by eliopinho** [comment]
im going test again :)

**Comment by Shadowss** [comment]
Have fun ;)

**Comment by eliopinho** [comment]
mate, its working
i found a new village, sent troops made by another one
but only dies imperian..

should die one type off troop, after another type off troop.. and the last off all troops die the hero..
don't ?

the troops are made fair by another village

i sent 500 imperian and 300 caesaris
test

**Comment by Shadowss** [comment]
I first post I explain you how work the script for starvation now i can explain how work script for killing troops ;)

After kill some imperian will start to kill caesaris :) as I told you , you must to play fair to make that script work :+1: 

In real travian is the same i think (not kill random troops)

Frist kill enforcement troop - if you send like you (imperian + caesaris in same enforcement) , if you send first imperian and your starvation will -200 start kill imperian and if send again caesaris and starvation change to -900 start first to kill caesaris (troop that consume more crop)
Second kill first type of troop (imperian in your case)
Third kill second type of troop (caesaris in your case)
Forth : kill your own troop if you have (first type of troop)
Fift and last kill your HERO

**Pull request merged**
