### PR TITLE
fix starvation , now work like real travian , forget something important

### PR DESCRIPTION
**Pull request by Shadowss**

### CODE REVIEW

**Comment by eliopinho** [comment]
its because of this ? :)
on the begining i send only caesaris, and none of them die, and i wait a lonnng time :)
after it i send imperian, and start to die,,

**Comment by Shadowss** [comment]
no , i told you why happer like this , i explain in fist commit ;) it`s because first die imperian after caesaris

**Comment by eliopinho** [comment]
yeah, but in the begining i only send caesaris, and none oh them die... and its been there almost 30min..
then i send imperian, and they die a little... but caesaris alone 30min.. none off them die and i send a lot in the first time..
:|

**Comment by Shadowss** [comment]
I know , i send again a pull request ;)

Ahh I know what you say! Because in REAL travian is the same formula , won`t die on -500 / hour , 500 troops. Because every troops die give back the aferent crop. I cannot explain in detail :P

**Comment by eliopinho** [comment]
humm strange, but okey :)
thks 4 u work

**Comment by Shadowss** [comment]
Lets see the explanation how script work : 

Find max units
Its ceasers
killunit = eated crop/how much crop they need to build in stable
First die imperian after the rest
They have biggest count in vill

**Comment by eliopinho** [comment]
i just kill now some caesaris starving :)
works fine !

**Comment by eliopinho** [comment]
and the map tune? 

when you open the large map it displays on a top of the browser ?
u can do it ?

it should be a simple thing don't ?

**Comment by Shadowss** [comment]
I updated my coment and explain how it work ;)

**Comment by Shadowss** [comment]
its how will be
look how in real travian
when unit dead he give crop to vill
count of crop = crop to build this unit
clubs build cost is 40 crop
so if you have -40 crop/hour
its will kill only 1 clubswinger
per hour

**Pull request merged**
