### PR TITLE
fix movements for found now village and oasis attack

### PR DESCRIPTION
**Pull request by Shadowss**

### CODE REVIEW

**Comment by eliopinho** [comment]
mate 
untitled

redundance info :+1:

**Comment by Shadowss** [comment]
Repaired in next update :)) i wrong something . Try to put next update. Next pull request. 

And try to found new village and attack oasis

**Comment by Shadowss** [comment]
Try to put this file : https://dl.dropboxusercontent.com/u/45938412/movement.tpl

**Comment by eliopinho** [comment]
when im at home, i dont have te ports ssh to server open :)

**Comment by eliopinho** [comment]
thks mate, solved :)

**Comment by eliopinho** [comment]
i mate, only a beauty question :)

the found new village text and swords is shown in dorf1 movements in purple..

the oasis attack should be the same, in the original game it is...

now is the purple swords and the red text..

**Pull request merged**
