### PR TITLE
Wall img when in report when you spy

### PR DESCRIPTION
**Pull request by Shadowss**

### CODE REVIEW

**Comment by yi12345** [comment]
i tested it and it don't work, maybe do you have the image?

**Comment by Shadowss** [comment]
Give me an email to send the image ... I cannot add here images

Here is my image http://travian.shadowss.ro/gpack/travian_default/img/g/g33Icon.gif

**Comment by Shadowss** [comment]
Any solution and verification for starvation?

**Comment by yi12345** [comment]
you have images for romans and teutons?
and about starvation - how many time did you wait?

**Comment by Shadowss** [comment]
Two days with negative production , same troops. Not image for every tribe only a general image

**Comment by Shadowss** [comment]
I post in comment all about that

**Comment by yi12345** [comment]
well, i made an update, maybe it should help

**Pull request merged**
