### PR TITLE
fix movements for found now village and oasis attack

### PR DESCRIPTION
**Pull request by Shadowss**
Must to be fixed in Templates/Build/16_incomming.tpl , because not show troops that are coming , only attacker view in rally poing what attack , the defender don`t show what coming , only on dorf1

### CODE REVIEW

**Comment by eliopinho** [comment]
thks a lot :)

**Comment by eliopinho** [comment]
now on the map? you don't know?

**Comment by Shadowss** [comment]
I send the fix to yi12345 for movements only in page dorf1.php and movements.tpl. Now you can view incoming attacks on oasis and found new village.

Also if yi12345 knows must to repair 16_incoming.tpl because not show what comes (attack or raid or etc) if your oasis is under attack , raid or etc. Doesn`t apper anythink.

About map , i don`t have any ideea , i try to fix this bug 2 days nothing .... i don`t know how to fix it ...

**Comment by eliopinho** [comment]
ok mate no prob :|

and my hero situation , dont work..

**Pull request closed without merging**
